name: ternakin
description: "A new Flutter project."
publish_to: 'none'
homepage:
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">= 3.0.0 <3.32.0"

dependencies:
  intl: ^0.18.1
  flutter:
    sdk: flutter
  fl_chart: ^0.64.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  image_picker: ^0.8.7
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.9
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.2.1
  google_sign_in: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10 

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/cipaaa.png
    - .env

flutter_native_splash:
  color: "#ffffff"     
  image: assets/images/logo.png
  branding: assets/images/google.png 
  android: true
  ios: true
  fullscreen: true
  web: true
