// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz9znVmL11vHAZ7hiBhw2Fckny1Or6MVQ',
    appId: '1:711073168851:web:4a260b4ff0cfdc97aa4326',
    messagingSenderId: '711073168851',
    projectId: 'chickdev-639f5',
    authDomain: 'chickdev-639f5.firebaseapp.com',
    storageBucket: 'chickdev-639f5.firebasestorage.app',
    measurementId: 'G-YE48KENJ1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy3cQqYk_H9gcQ1__fLo9sos2QQ_cmXN0',
    appId: '1:711073168851:android:b6f1f7d431a0a7b5aa4326',
    messagingSenderId: '711073168851',
    projectId: 'chickdev-639f5',
    storageBucket: 'chickdev-639f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhQmkwXMicdUh9kw6h3gxNWup3YuuTKxY',
    appId: '1:711073168851:ios:0196e5a3a7a7af57aa4326',
    messagingSenderId: '711073168851',
    projectId: 'chickdev-639f5',
    storageBucket: 'chickdev-639f5.firebasestorage.app',
    iosBundleId: 'com.example.ternakin',
  );
}
